# Generated by Django 5.2.16 on 2026-08-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporthouseprofile',
            name='fabric_specialization',
        ),
        migrations.RemoveField(
            model_name='exporthouseprofile',
            name='iec',
        ),
        migrations.RemoveField(
            model_name='subcontractorprofile',
            name='fabric_specialization',
        ),
    ]
