# Generated by Django 5.2.16 on 2026-08-05 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_exporthouseprofile_fabric_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('process_type', models.CharField(choices=[('Weaving', 'Weaving'), ('Dyeing', 'Dyeing'), ('Printing', 'Printing'), ('Embroidery', 'Embroidery'), ('Stitching/Garmenting', 'Stitching/Garmenting'), ('Washing', 'Washing'), ('Finishing', 'Finishing')], max_length=50)),
                ('urgency_level', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Immediate Dispatch', 'Immediate Dispatch')], max_length=50)),
                ('raw_material_provided', models.CharField(max_length=255)),
                ('total_quantity', models.FloatField()),
                ('unit_of_measurement', models.CharField(choices=[('Meters', 'Meters'), ('Kgs', 'Kgs'), ('Pieces', 'Pieces'), ('Rolls', 'Rolls'), ('Yards', 'Yards')], max_length=50)),
                ('expected_delivery_date', models.DateField()),
                ('pickup_delivery_location', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_negotiable', models.BooleanField(default=False)),
                ('technical_specifications', models.TextField(blank=True)),
                ('design_document', models.FileField(blank=True, null=True, upload_to='job_designs/')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
