# Generated by Django 5.2.16 on 2026-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_job_bidding_end_time_job_bidding_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorprofile',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subcontractorprofile',
            name='verification_status',
            field=models.CharField(default='UNVERIFIED', max_length=50),
        ),
    ]
