# Generated by Django 5.2.16 on 2026-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subcontractorprofile_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporthouseprofile',
            name='gstin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
