# Generated by Django 5.2.14 on 2026-08-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jobbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=100, unique=True)),
                ('subcontractor_name', models.CharField(max_length=255)),
                ('subcontractor_id_type', models.CharField(max_length=100)),
                ('subcontractor_id_number', models.CharField(max_length=100)),
                ('destination_address', models.TextField(blank=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_challans', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.job')),
                ('subcontractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_challans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChallanMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.challan')),
            ],
        ),
    ]
