# Generated by Django 5.2.14 on 2026-08-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_challan_challanmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='subcontractor_contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='challan',
            name='subcontractor_contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subcontractorprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subcontractorprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subcontractorprofile',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
