# Generated by Django 5.2.14 on 2026-08-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_challan_subcontractor_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporthouseprofile',
            name='authorized_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='exporthouseprofile',
            name='company_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
    ]
