# Generated by Django 5.2.14 on 2026-08-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_exporthouseprofile_authorized_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challanmaterial',
            name='taxable_value_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
