# Generated by Django 5.2.14 on 2026-08-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_challanmaterial_taxable_value_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='gate_in_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
