# Generated by Django 5.2.14 on 2026-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_challan_gate_in_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='completion_proof',
            field=models.TextField(blank=True),
        ),
    ]
