# Generated by Django 5.2.14 on 2026-08-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_job_completed_at_job_completion_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='return_challan_generated',
            field=models.BooleanField(default=False),
        ),
    ]
