# Generated by Django 5.2.14 on 2026-08-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_challan_return_challan_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcontractorprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='subcontractorprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='completion_proof',
            field=models.ImageField(blank=True, null=True, upload_to='completion_proofs/'),
        ),
    ]
